language: node_js
node_js:
  - "0.12"
cache:
  directories:
    - node_modules
    - $(npm config get prefix)/bin/grunt-cli
    - $(npm config get prefix)/bin/web-component-tester
    - $(npm config get prefix)/bin/firebase-tools
before_script:
  - npm install -g grunt-cli
  - npm install -g web-component-tester
  - grunt build
script:
  - wct --plugins sauce
after_success:
  - grunt clean:deploy
before_deploy:
  - npm install -g firebase-tools
  - chmod +x configs/deploy.sh
  - chmod +x configs/deploy-staging.sh
deploy:
  - provider: script
    script: configs/deploy.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: configs/deploy-staging.sh
    skip_cleanup: true
    on:
      branch: staging