language: node_js
node_js:
  - "0.12"
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm install -g grunt-cli
before_script:
  - grunt build
  - npm install -g web-component-tester
  - set -o pipefail
script:
  - wct --plugins sauce | cat
after_success:
  - grunt clean:deploy
before_deploy:
  - npm install -g firebase-tools
  - chmod +x configs/deploy.sh
  - chmod +x configs/deploy-staging.sh
deploy:
  - provider: script
    script: configs/deploy.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: configs/deploy-staging.sh
    skip_cleanup: true
    on:
      branch: staging