language: node_js
node_js:
  - "0.12"
cache:
  directories:
    - node_modules
before_script:
  - npm install -g grunt-cli
  - npm install -g web-component-tester
  - npm install -g firebase-tools
  - grunt build
script:
  - wct --plugins sauce
before_deploy:
  - chmod +x configs/deploy.sh
  - chmod +x configs/deploy-staging.sh
deploy:
  - provider: script
    script: configs/deploy.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: configs/deploy-staging.sh
    skip_cleanup: true
    on:
      branch: staging